# If you change the key names, do a find/replace to update their usage throughout the rest of XTools
#
# Format for individual entries:
#
#   Tool name:
#       regex: Regular expression to match against edit summary
#       tag: Tag name for the tool, if applicable. See [[Special:Tags]] for full list
#       single_tag: Set to true to look for edits that *only* have this tag. This is used primarily
#           for rollback, so that you can see true system rollback and not edits by other tools
#           that use rollback.
#       link: Wiki link to tool documentation
#       label: Text to use as the label, defaults to the tool's key. Use this for translations.
#       revert: If the tool is used *only* to revert edits (and not also issue talk page
#           notifications, etc.), set this to `true`. If the tool is capable of reverting
#           edits, set 'revert' to regex that would only account for reverts.
#           See the 'Twinkle' entry for an example. The revert-only regex is necessary
#           for ArticleInfo and elsewhere, so as to differentiate edits that added content
#           from edits that restored content.
#       contribs: Set to true to include edits with the given tool in non-automated contributions.
#           For example, we do this for ProveIt, because that tool often includes prose that was
#           added by the user, and not entirely a semi-automated edit.
#
# Either 'regex' or 'tag' are required. In some cases you might want to include both,
#   say if older versions of the tool did not add tags to the edits.
parameters:
  automated_tools:

    # These tools work on multiple wikis. These should probably include tags
    #   as the regex may not apply to non-English wikis.
    # You can also set wiki-specific regex that will get merged into the global regex.
    # Other local values such as link, tag and revert are overriden, not merged into the global value.
    # See 'Huggle' under 'global' and 'en.wikipedia.org' for an example.
    global:
        Generic rollback:
            tag: mw-rollback
            single_tag: true
            regex: '^(\[\[Help:Reverting\|Reverted\]\]|Reverted) edits by \[\[Special:(Contribs|Contributions)\/.*?\|.*?\]\] \(\[\[User talk:.*?\|talk\]\]\) to last (version|revision) by .*'
            link: Special:MyLanguage/Project:Rollback
            revert: true
        Undo:
            tag: mw-undo
            single_tag: true
            tag_excludes:
                - mw-rollback
                - huggle
            regex: '^(Undid|Undo|\[\[WP:UNDO\|Undid\]\]) revision \d+ by \[\[Special:(Contribs|Contributions)\/.*?\|.*?\]\]'
            link: Special:MyLanguage/Project:Undo
            # This is not considered a revert because you can undo
            # any arbitrary revision, not just the previous one.
        Redirect:
            tag: mw-new-redirect
            link: mw:Special:MyLanguage/Help:Redirects
        Huggle:
            regex: '\(\[\[WP:HG'
            tag: huggle
            link: w:en:Wikipedia:Huggle
        WPCleaner:
            regex: 'WP:CLEANER|WPCleaner\]\]|\[\[\Wikipedia:DPL|\[\[WP:WCW\]\] project \('
            tag: WPCleaner
            link: Special:MyLanguage/Project:WPCleaner
        IABot:
            tag: 'OAuth CID: 678'
            link: Special:MyLanguage/User:InternetArchiveBot
        HotCat:
            regex: '\|HotCat\]\]|Gadget-Hotcat(?:check)?\.js\|Script|\]\] via HotCat'
            link: Special:MyLanguage/Project:HotCat
        Cat-a-lot:
            regex: '\[\[Help:Cat-a-lot\|Cat-a-lot\]\]'
            link: commons:Cat-a-lot
        Global rename:
            regex: 'Automatically moved page while renaming the user'
            link: meta:Special:MyLanguage/Global renamers
        Page move:
            regex: 'moved page \[\[(?!.*?WP:AFCH)|moved \[\[.*?\]\] to \[\['
            link: mw:Special:MyLanguage/Help:Moving a page
        Popups:
            regex: 'Wikipedia:Tools\/Navigation_popups|popups'
            link: w:en:Project:Popups
        Commons file rename:
            regex: 'COM:FR\|File renamed\]\]:'
            link: c:Special:MyLanguage/Commons:File renaming
        Commons duplicate file:
            regex: 'COM:Duplicate\|Duplicate'
            link: c:Commons:Duplicate
        reFill:
            regex: 'User:Zhaofeng Li\/Reflinks|WP:REFILL|en:WP:REFILL'
            link: Project:ReFill
        WikiLove:
            tag: wikilove
            link: mw:Special:MyLanguage/Extension:WikiLove
        Content translation:
            tag: contenttranslation
            regex: 'Created by translating the page'
            link: mw:Special:MyLanguage/Content translation
            contribs: true
        ProveIt:
            tag: ProveIt edit
            link: commons:Help:Gadget-ProveIt
            contribs: true
        AutoWikiBrowser:
            tag: AWB
            regex: 'using \[\[(Wikipedia|WP|Project):(AWB|AutoWikiBrowser)'
            link: Project:AutoWikiBrowser

    # Per-language lists. This generally only includes native MediaWiki actions.
    ar:
        Undo:
            regex: 'الرجوع عن التعديل \d+ بواسطة'
    de:
        Undo:
            regex: 'Änderung \d+ von \[\[.*?rückgängig gemacht'
            label: Rückgängig
        Generic rollback:
            regex: 'Änderungen von \[\[.*?die letzte Version von \[\[.*?zurückgesetzt'
            label: Zurücksetzen
        Page move:
            regex: 'verschob die Seite \[\[.*?nach'
            label: Seite verschieben
        Redirect:
            regex: 'Weiterleitung nach \[\[.*?erstellt'
            label: Weiterleitung
    ko:
        Undo:
            regex: '판 편집을 되돌림'
            label: '편집 취소'
        Generic rollback:
            regex: '(의 마지막 판으로 되돌림|의 편집을 전부 되돌림)'
            label: '되돌리기'
        Page move:
            regex: '문서로 이동했습니다'
            label: '문서 이동'
    pt:
        Page move:
            regex: 'moveu \[\[.*?para \[\['
            label: Movimentos de página
        Content translation:
            regex: 'Criado ao traduzir a página'
            label: Tradução de Conteúdos
        Redirect:
            label: Redirecionamentos
            link: Ajuda:Guia de edição/Redirecionar páginas

    # Per-wiki lists
    ar.wikipedia.org:
        Generic rollback:
            regex: 'استرجاع تعديلات.*حتى آخر نسخة بواسطة'
        Huggle:
            regex: '\(\[\[ويكيبيديا:هغل'
            link: ويكيبيديا:هغل
            label: هغل
        Page move:
            regex: 'نقل.*?صفحة \[\[.*?إلى \[\['
            link: ويكيبيديا:نقل_صفحة
            label: نقل_صفحة
        AutoWikiBrowser:
            regex: 'Project:أوب'
            link: ويكيبيديا:أوتوويكي_براوزر
        HotCat:
            regex: 'باستخدام \[\[ويكيبيديا:المصناف الفوري'
            link: ويكيبيديا:المصناف الفوري
            label: المصناف الفوري
        Popups:
            link: ويكيبيديا:المنبثقات
            label: المنبثقات
        WPCleaner:
            link: ويكيبيديا:وب_كلينر
            label: وب_كلينر
        Rater:
            regex: '\[\[(:User:FShbib\/المقيم|ويكيبيديا:المقيم)'
            link: مستخدم:FShbib/المقيم
    commons.wikimedia.org:
        UploadWizard:
            regex: '^User created page with UploadWizard$'
            link: Special:MyLanguage/Commons:Upload Wizard
        VisualFileChange:
            regex: 'Using \[\[COM:VFC'
            tag: VisualFileChange
            link: Special:MyLanguage/Help:VisualFileChange.js
        AjaxQuickDelete:
            regex: '^(This category needs discussion|\[\[:.*?\]\] needs discussion|Starting category discussion|Nominating for deletion|\[\[:.*?\]\] has been nominated for deletion|Starting deletion request|Listing \[\[.*?\]\])$|#Autoreport by AjaxQuickDelete|^Updating redirect while processing'
            link: Special:MyLanguage/Help:Nominate_for_deletion
        QuickDelete:
            regex: '^(Marking as possible copyvio because|Notification of possible copyright violation for|\[\[.*?\]\] does not have a source|Please send permission for \[\[|\]\] does not have a license)|^(File has no source|Missing permission)$'
            link: Special:MyLanguage/Help:QuickDelete
        POTY:
            regex: '\[\[Help:(?:Gadget-)EnhancedPOTY.js|POTY App\]\]$'
            link: Help:Gadget-EnhancedPOTY.js
        Flickr2Commons:
            regex: 'via \[\[(?:Special:MyLanguage\/)?Commons:Flickr2Commons'
            link: Special:MyLanguage/Flickr2Commons
        Android Commons:
            regex: '^Uploaded using Android Commons app$'
            link: Special:MyLanguage/Commons:Mobile_app
        Commonsist:
            regex: '^commonist \d\.\d'
            link: Special:MyLanguage/Commons:Commonist
        RenameLink:
            regex: '^\(\[\[Help:RenameLink\|Script'
            link: Special:MyLanguage/Help:RenameLink
        Geograph2commons:
            regex: 'Transferred from geograph.co.uk using'
            link: Special:GoToInterwiki/toollabs:geograph2commons
        SettingsManager:
            regex: '\[\[MediaWiki:Gadget-SettingsManager.js\|SettingsManager'
            link: MediaWiki:Gadget-SettingsManager.js
        RotateLink:
            regex: '\(\[\[Help:RotateLink\|Script'
            link: Help:RotateLink
    de.wikipedia.org:
        Generic rollback:
            link: Wikipedia:Zurücksetzen
        Page move:
            link: Hilfe:Seite verschieben
        Redirect:
            link: Wikipedia:Weiterleitung
        Popups:
            regex: 'Wikipedia:Helferlein\/Navigation-Popups\|Popups'
            link: Wikipedia:Helferlein/Navigation-Popups
            label: Navigation-Popups
    de.wiktionary.org:
        Einfügen-Erweiterung:
            regex: \[\[Hilfe:Einfügen-Erweiterung\|
            link: Hilfe:Einfügen-Erweiterung
    en.wikipedia.org:
        Pending changes revert:
            regex: '^(\[\[Help:Reverting\|Reverted\]\]|Reverted) \d+ (\[\[Wikipedia:Pending changes\|pending\]\]|pending) edits? (to revision \d+|by \[\[Special:(Contribs|Contributions)\/.*?\|.*?\]\])'
            link: Project:Pending changes
            revert: true
        Bot revert:
            regex: '^Reverting possible (vandalism|test edit).*by.*\(Bot|BOT( EDIT)?\)$|^BOT (- )?(Reverted edits? by|rv)|^vandalism from \[\[.*?\(\d+\) - reverted'
            link: Project:Bots
            revert: true
        Huggle: # This gets merged into the global Huggle definition (the revert regex here is enwiki-specific)
            revert: 'Reverted edits by.*?WP:HG'
        Page curation:
            regex: 'using \[\[Wikipedia:Page Curation\|Page Curation'
            link: Project:Page curation
        Twinkle:
            regex: '(Wikipedia|WP):(TW|TWINKLE|Twinkle|FRIENDLY)'
            link: Project:Twinkle
            revert: '(Reverted to revision|Reverted \d+ edits).*(WP:(TW|TWINKLE|Twinkle)|Wikipedia:Twinkle)'
        STiki:
            regex: 'WP:(STiki|STIKI)'
            link: w:en:Wikipedia:STiki
            revert: Reverted \d+.*WP:(STiki|STIKI)
        Igloo:
            regex: 'Wikipedia:Igloo'
            link: w:en:Wikipedia:Igloo
        AFCH:
            regex: 'WP:(AFCH|AFCHRW)'
            link: Project:AFCH
        Checklinks:
            regex: 'using \[\[w:WP:CHECKLINKS'
            link: Project:CHECKLINKS
        Dab solver:
            regex: 'using \[\[(tools:~dispenser\/view\/Dab_solver|WP:DABSOLVER)\|Dab solver|(Disambiguated|Unlinked|Help needed): \[\[|Disambiguated \d+ links|Repaired link.*?\[\[Wikipedia:WikiProject Disambiguation\|please help'
            link: Project:DABSOLVER
        Dabfix:
            regex: 'using \[\[tools:~dispenser\/cgi-bin\/dabfix.py'
            link: Special:GoToInterwiki/toollabs:dispenser/cgi-bin/dabfix.py
        Reflinks:
            regex: '\[\[(tools:~dispenser\/view\/Reflinks|WP:REFLINKS)\|Reflinks'
            link: Project:REFLINKS
        WikiPatroller:
            regex: 'User:Jfmantis\/WikiPatroller'
            link: User:Jfmantis/WikiPatroller
        delsort:
            regex: 'Wikipedia:WP:FWDS|WP:FWDS|User:APerson\/delsort\|delsort.js|User:Enterprisey\/delsort\|assisted'
            link: WP:DELSORT
        Ohconfucius script:
            regex: '\[\[(User:Ohconfucius\/.*?|WP:MOSNUMscript)\|script'
            link: Project:MOSNUMscript
        OneClickArchiver:
            regex: '\[\[(User:Equazcion\/OneClickArchiver|User:Technical 13\/1CA)\|OneClickArchiver'
            link: Project:OneClickArchiver
        editProtectedHelper:
            regex: 'WP:EPH|EPH'
            link: Project:EPH
        WikiLove:
            regex: 'new WikiLove message'
            link: Project:WikiLove
        AutoEd:
            regex: 'using \[\[(Wikipedia|WP):AutoEd\|AutoEd'
            link: Project:AutoEd
        Mike's Wiki Tool:
            regex: User:MichaelBillington\/MWT\|MWT|Mike's Wiki Tool
            link: Project:Mike's Wiki Tool
        Global replace:
            regex: '\(\[\[c:GR\|GR\]\]\) '
            link: commons:Commons:File renaming/Global replace
        Admin actions:
            regex: '^(Protected|Changed protection).*?\[[Ee]dit=|^Removed protection from|^Configured pending changes.*?\[[Aa]uto-accept|^Reset pending changes settings'
            link: Project:Administrators
        CSD Helper:
            regex: '\(\[\[User:Ale_jrb\/Scripts\|CSDH'
            link: Project:CSDH
        Find link:
            regex: 'using \[\[User:Edward\/Find link\|Find link'
            link: User:Edward/Find link
        responseHelper:
            regex: '\(using \[\[User:MusikAnimal\/responseHelper\|responseHelper'
            link: User:MusikAnimal/responseHelper
        Advisor.js:
            regex: '\(using \[\[(User:Cameltrader#Advisor.js|User:PC-XT\/Advisor)\|Advisor.js'
            link: WP:ADVISOR
        AfD closures:
            regex: '^\[\[Wikipedia:Articles for deletion\/.*?closed as'
            link: Project:Articles for deletion
        Sagittarius:
            regex: '\(\[\[User:Kephir\/gadgets\/sagittarius\|'
            link: User:Kephir/gadgets/sagittarius
        Redirect:
            regex: '\[\[WP:AES\|←\]\]Redirected page to \[\[.*?\]\]'
            link: Project:Redirect
        Dashes:
            regex: 'using a \[\[User:GregU\/dashes.js\|script'
            link: User:GregU/dashes
        SPI Helper:
            regex: '^(Archiving case (to|from)|Adding sockpuppetry (tag|block notice) per) \[\[Wikipedia:Sockpuppet investigations'
            link: User:Timotheus Canens/spihelper.js
        User:Doug/closetfd.js:
            regex: '\(using \[\[User:Doug\/closetfd.js'
            link: User:Doug/closetfd.js
        autoFormatter:
            regex: 'using (\[\[:meta:User:TMg\/autoFormatter|autoFormatter)'
            link: meta:User:TMg/autoFormatter
        Citation bot:
            regex: '\[\[WP:UCB\|Assisted by Citation bot'
            link: Project:UCB
        Red Link Recovery Live:
            regex: '\[\[w:en:WP:RLR\|You can help!'
            link: en:WP:RLR
        Script Installer:
            regex: '\[\[User:Equazcion\/ScriptInstaller\|Script Installer'
            link: User:Equazcion/ScriptInstaller
        findargdups:
            regex: '\[\[:en:User:Frietjes\/findargdups'
            link: User:Frietjes/findargdups
        closemfd.js:
            regex: '\(using \[\[User:Doug\/closemfd.js'
            link: User:Doug/closemfd.js
        DisamAssist:
            regex: 'using \[\[User:Qwertyytrewqqwerty\/DisamAssist'
            link: User:Qwertyytrewqqwerty/DisamAssist
        Vada:
            regex: '\(\[\[WP:Vada\]\]\)'
            link: Project:Vada
        stubtagtab.js:
            regex: 'using \[\[User:MC10\/stubtagtab.js'
            link: User:MC10/stubtagtab.js
        AutoSpell:
            regex: 'User:Symplectic_Map\/AutoSpell\|Script-assisted'
            link: User:Symplectic_Map/AutoSpell
        Draftify:
            regex: '\(\[\[WP:DFY\|DFY\]\]\)'
            link: Project:DFY
        AFC/R HS:
            regex: 'Using \[\[User:PhantomTech\/scripts\/AFCRHS.js\|AFC\/R HS'
            link: User:PhantomTech/scripts/AFCRHS.js
        For the Common Good:
            regex: 'WP:FTCG\|FtCG'
            link: Project:FTCG
        OrphanStatus:
            regex: '\[\[User:Technical_13\/Scripts\/OrphanStatus\|'
            link: User:Technical13/Scripts/OrphanStatus.js
        The Wikipedia Adventure:
            regex: 'simulated automatically as part of \[\[WP:The Wikipedia Adventure\|'
            link: Project:TWA
        OABot:
            tag: 'OAuth CID: 817'
            link: Project:OABOT
        XFDCloser:
            regex: '\[\[WP:XFDC\|XFDcloser'
            link: User:Evad37/XFDcloser.js
        Rater:
            regex: '\[\[User:(Evad37\/rater.js|Kephir\/gadgets\/rater)'
            link: User:Evad37/rater.js
        revdel:
            regex: 'using \[\[User:Primefac\/revdel'
            link: User:Primefac/revdel
        draft-sorter:
            regex: '\(draft-sorter\.js\)'
            link: User:Enterprisey/draft-sorter
        Xunlink:
            regex: '\(\[\[User:Evad37\/Xunlink'
            link: User:Evad37/Xunlink
        MoveToDraft:
            regex: '\[\[User:Evad37\/MoveToDraft\.js\|via script'
            link: User:Evad37/MoveToDraft
        Content translation:
            link: Wikipedia:Content translation tool
        ProveIt:
            regex: 'with \[\[Wikipedia:ProveIt'
            link: Wikipedia:ProveIt
        JWB:
            regex: 'via (JWB|\[\[WP:JWB\]\])'
            link: WP:JWB
        Snuggle:
            regex: 'WP:Snuggle\|Sn\]\]'
            link: Project:Snuggle
    ko.wikipedia.org:
        AutoWikiBrowser:
            regex: '위키백과:AWB\|AWB|(Wikipedia|WP|Project):(AWB|AutoWikiBrowser)'
            link: 위키백과:AWB
            label: 오토위키브라우저
        Popups:
            regex: '\[\[백:팝업\|NavPop\]\]'
            link: 백:팝업
            label: 내비게이션 팝업
        Twinkle:
            regex: '\[\[위키백과:도구\/트윙클\|TW\]\]|(Wikipedia|WP):(TW|TWINKLE|Twinkle|FRIENDLY)'
            link: 위키백과:도구/트윙클
            label: 트윙클
        WikiLove:
            regex: '새 위키사랑 글'
            link: 위키백과:위키사랑
            label: 위키사랑
    pt.wikipedia.org:
        Undo:
            regex: 'Desfeita a edição \d+ de \[\['
        FastButtons:
            regex: '\|FastButtons\]\]'
            link: Wikipédia:FastButtons
        Script de ajustes:
            regex: 'usando \[\[[Uu]ser:Luizdl/Script de ajustes.js'
            link: User:Luizdl/Script de ajustes.js
        Automatic Page Corrector:
            tag: apc
            regex: '\+correções \[\[WP:SR\|semiautomáticas'
            link: Wikipédia:Scripts/APC
        Popups:
            link: Wikipédia:Software/Popups de navegação
            label: Popups de navegação
        Page move:
            link: Ajuda:Guia de edição/Mover páginas
        Generic rollback:
            link: Wikipédia:Reversores
            label: Reversores
