# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    disabled_tool_subscriber:
        class: AppBundle\EventSubscriber\DisabledToolSubscriber
        arguments: ['@service_container']

    rate_limit_subscriber:
        class: AppBundle\EventSubscriber\RateLimitSubscriber
        arguments: ['@service_container']

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ["@service_container", "@request_stack", "@session"]
        public: false
        tags:
            - { name: twig.extension }
    app.api_helper:
        class: AppBundle\Helper\ApiHelper
        arguments: ["@service_container"]
        public: true
        tags:
          - {name: api.helper}
    app.automated_edits_helper:
        class: AppBundle\Helper\AutomatedEditsHelper
        arguments: ["@service_container"]
        public: true
        tags:
          - {name: automatededits.helper}
