parameters:
  tools:
    ec: ec
    articleinfo: articleinfo
    pages: pages
    topedits: topedits
    blame: blame
    autoedits: autoedits
    adminstats: adminstats
    adminscore: adminscore
    es: es
    rfx: rfx
    rfxvote: rfxvote
    bash: bash
    sc: sc