imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ['rate_limit', 'blacklist', 'main']
    handlers:
        rate_limit:
            # log all messages (since debug is the lowest level)
            level: info
            type: stream
            path: '%kernel.logs_dir%/rate_limit.log'
            channels: [rate_limit]
        blacklist:
            # log all messages (since debug is the lowest level)
            level: info
            type: stream
            path: '%kernel.logs_dir%/blacklist.log'
            channels: ['blacklist']
        main:
            type: fingers_crossed
            action_level: critical
            handler: main_handler
        main_handler:
            type: group
            members: [console, log_file, mailer]
        console:
            type: console
            level: debug
            process_psr_3_messages: false
        log_file:
            type: stream
            level: info
            path: '%kernel.logs_dir%/%kernel.environment%.log'
        mailer:
            type: deduplication
            time: 300
            handler: swift
        swift:
            type: swift_mailer
            level: critical
            from_email: '%mailer.from_email%'
            to_email: '%mailer.to_email%'
            subject: '[XTools] Fatal error: %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
