parameters:
  tools:
    # This is the order they will appear in the interface.
    - EditCounter
    - PageInfo
    - Authorship
    - Blame
    - GlobalContribs
    - Pages
    - TopEdits
    - AutoEdits
    - CategoryEdits
    - AdminStats
    - LargestPages
    - AdminScore
    - EditSummary
    - Quote
    - SimpleEditCounter
